name: Sync labels

on:
  push:
    branches:
    - main
    paths:
    - .github/labels.yml

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Sync labels
      uses: crazy-max/ghaction-github-labeler@v4.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        yaml-file: .github/labels.yml
        skip-delete: false
        dry-run: false
        # exclude: |
